"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const Governments_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Models/Governments"));
const Database_1 = __importDefault(global[Symbol.for('ioc.use')]("Adonis/Lucid/Database"));
const Seeder_1 = __importDefault(global[Symbol.for('ioc.use')]("Adonis/Lucid/Seeder"));
class default_1 extends Seeder_1.default {
    async run() {
        await Database_1.default.rawQuery('SET FOREIGN_KEY_CHECKS=0');
        await Governments_1.default.createMany([
            {
                name: 'Kelurahan Cipaisan',
                logo: null,
                alias: 'CIPAISAN',
                slug: 'cipaisan',
                address: 'Jl. Jend. Ahmad Yani No.36, Cipaisan, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41112',
                email: null,
                phone: '(0264) 200036',
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Dinas Ketenagakerjaan dan Transmigrasi',
                logo: null,
                alias: 'DISNAKERTRANS',
                slug: 'disnakertrans',
                address: 'Jl. Veteran No. 03, Ciseureuh, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41115',
                email: null,
                phone: '(0264) 200459',
                fax: '(0264) 200459',
                url: 'https://disnakertrans.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kelurahan Purwamekar',
                logo: null,
                alias: 'PURWAMEKAR',
                slug: 'purwamekar',
                address: 'Purwamekar, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41119',
                email: null,
                phone: null,
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kelurahan Cisereuh',
                logo: null,
                alias: 'CISEREUH',
                slug: 'cisereuh',
                address: 'Jl. Veteran No.229, Ciseureuh, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41118',
                email: null,
                phone: '(0264) 207612',
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Dinas Kearsipan dan Perpustakaan',
                logo: null,
                alias: 'DISIPUSDA',
                slug: 'disipusda',
                address: 'Jl. Veteran, No. 01, Komplek Perum Griya Asri, Ciseureuh, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41118',
                email: 'info@arsipda.purwakartakab.go.id',
                phone: '(0264) 212575',
                fax: null,
                url: 'https://disipusda.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kelurahan Tegalmunjul',
                logo: null,
                alias: 'TEGALMUNJUL',
                slug: 'tegalmunjul',
                address: 'Jl. Ipik Gandamanah No.81, Tegalmunjul, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41116',
                email: null,
                phone: '(0264) 231934',
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kelurahan Munjuljaya',
                logo: null,
                alias: 'MUNJULJAYA',
                slug: 'munjuljaya',
                address: 'Munjuljaya, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41117',
                email: null,
                phone: null,
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Dinas Pangan dan Pertanian',
                logo: null,
                alias: 'DISPANGTAN',
                slug: 'dispangtan',
                address: 'Jl. Surawinata No.30, Nagri Tengah, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41114',
                email: 'dispangtan@purwakartakab.go.id',
                phone: '(0264) 200069',
                fax: null,
                url: 'https://pertanian.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kecamatan Pondoksalam',
                logo: null,
                alias: 'PONDOKSALAM',
                slug: 'pondoksalam',
                address: 'Jl. Terusan Kapten Halim Km.16, Salam Mulya, Kec. Pondoksalam, Kabupaten Purwakarta, Jawa Barat 41115',
                email: 'kec_pondoksalam@pondoksalam.purwakartakab.go.id',
                phone: '08881688005',
                fax: null,
                url: 'https://pondoksalam.purwakartakab.go.id',
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Dinas Perikanan dan Peternakan',
                logo: null,
                alias: 'DISKANNAK',
                slug: 'diskannak',
                address: 'Jl. Suradireja No.28, Nagri Kaler, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41114',
                email: null,
                phone: '(0264) 200221',
                fax: null,
                url: 'https://diskannak.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Badan Perencanaan Pembangunan Penelitian dan Pengembangan Daerah',
                logo: null,
                alias: 'BAPPELITBANGDA',
                slug: 'bappelitbangda',
                address: 'Jl. Gandanegara No. 25, Kelurahan Nageri Kidul, Kecamatan Purwakarta, Kabupaten Purwakarta, Provinsi Jawa Barat. Kode Pos 41111',
                email: null,
                phone: '(0264) 8307463',
                fax: null,
                url: 'https://bappelitbangda.purwakartakab.go.id',
                type: 4,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Dinas Lingkungan Hidup',
                logo: null,
                alias: 'DLH',
                slug: 'dlh',
                address: 'Jl. Purnawarman Timur No.11 A, Sindangkasih, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41112',
                email: null,
                phone: '(0264) 212738',
                fax: null,
                url: 'http://silingkup.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kecamatan Wanayasa',
                logo: null,
                alias: 'WANAYASA',
                slug: 'wanayasa',
                address: 'Jl. Syahbandar No.1, Wanayasa, Kec. Wanayasa, Kabupaten Purwakarta, Jawa Barat 41174',
                email: null,
                phone: null,
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Badan Keuangan dan Aset Daerah',
                logo: null,
                alias: 'BKAD',
                slug: 'bkad',
                address: 'Jl. Ganda Negara No.25, Nagri Kidul, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41111',
                email: 'bkad@purwakartakab.go.id',
                phone: '081993040040',
                fax: null,
                url: 'https://bkad.purwakartakab.go.id',
                type: 4,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kecamatan Kiarapedes',
                logo: null,
                alias: 'KIARAPEDES',
                slug: 'kiarapedes',
                address: 'Jl. Raya Kiarapedes Km. 28, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat, 41175',
                email: 'kiarapedes@purwakartakab.go.id',
                phone: '628211211211',
                fax: null,
                url: 'https://kiarapedes.purwakartakab.go.id',
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: 'f5073c94-35b7-11ee-903d-00155d74ec2a',
                name: 'Sekretariat Daerah',
                logo: null,
                alias: 'SETDA',
                slug: 'setda',
                address: 'Jl. Gandanegara No.25, Nagri Kidul, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41111',
                email: 'setda@purwakartakab.go.id',
                phone: '0264200036',
                fax: null,
                url: 'https://setda.purwakartakab.go.id',
                type: 3,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Dinas Kependudukan dan Pencatatan Sipil',
                logo: null,
                alias: 'DISDUKCAPIL',
                slug: 'disdukcapil',
                address: 'Jl. Mr. Dr. Kusuma Atmaja No. 8, Nagri Tengah, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41114',
                email: null,
                phone: '(0264) 200640',
                fax: null,
                url: 'https://disdukcapil.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Sekretariat Dewan',
                logo: null,
                alias: 'SETWAN',
                slug: 'setwan',
                address: 'Jl. Pramuka, Mekargalih, Kec. Jatiluhur, Kabupaten Purwakarta, Jawa Barat 41152',
                email: null,
                phone: null,
                fax: null,
                url: 'https://dprd.purwakartakab.go.id',
                type: 3,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Satuan Polisi Pamong Praja',
                logo: null,
                alias: 'SATPOLPP',
                slug: 'satpolpp',
                address: 'Gg. Wortel No.29, Nagri Tengah, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41111',
                email: 'satpolpp@purwakartakab.go.id',
                phone: '6282299590127',
                fax: null,
                url: 'https://satpolpp.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Inspektorat',
                logo: null,
                alias: 'INSPEKTORAT',
                slug: 'inspektorat',
                address: 'Jl. Veteran No.147, Nagri Kaler, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41115',
                email: null,
                phone: '(0264) 201019',
                fax: '(0264) 201019',
                url: 'https://inspektorat.purwakartakab.go.id',
                type: 4,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kecamatan Bojong',
                logo: null,
                alias: 'BOJONG',
                slug: 'bojong',
                address: 'Jalan Raya Sawit, Sukamanah, Kec. Bojong, Kabupaten Purwakarta, Jawa Barat 41164',
                email: null,
                phone: null,
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Dinas Pemberdayaan Masyarakat dan Desa',
                logo: null,
                alias: 'DPMD',
                slug: 'dpmd',
                address: 'Jl. Purnawarman Timur No.8, Sindangkasih, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41112',
                email: 'dpmd@purwakartakab.go.id',
                phone: '+62 831-2089-7808',
                fax: null,
                url: 'https://dpmd.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kecamatan Darangdan',
                logo: null,
                alias: 'DARANGDAN',
                slug: 'darangdan',
                address: 'Jl. Raya Darangdan, Sadarkarya, Kec. Darangdan, Kabupaten Purwakarta, Jawa Barat 41163',
                email: null,
                phone: null,
                fax: null,
                url: 'http://darangdan.purwakartakab.go.id',
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Dinas Perumahan dan Kawasan Permukiman',
                logo: null,
                alias: 'DISPERKIM',
                slug: 'disperkim',
                address: 'Jalan K.K Singawinata No. 116, Nagri Kidul, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41111',
                email: 'disperkim@purwakartakab.go.id',
                phone: null,
                fax: null,
                url: 'https://disperkim.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kecamatan Pasawahan',
                logo: null,
                alias: 'PASAWAHAN',
                slug: 'pasawahan',
                address: 'Jl. Kapten Halim, Pasawahankidul, Kec. Pasawahan, Kabupaten Purwakarta, Jawa Barat 41172',
                email: null,
                phone: null,
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Dinas Pengendalian Penduduk dan Keluarga Berencana',
                logo: null,
                alias: 'DPPKB',
                slug: 'dppkb',
                address: 'Jl. Purnawarman Timur, Sindangkasih, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41112',
                email: null,
                phone: null,
                fax: null,
                url: 'https://dppkb.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kecamatan Sukatani',
                logo: null,
                alias: 'SUKATANI',
                slug: 'sukatani',
                address: 'Jl Raya Sukatani, Desa Sukatani, Kecamatan Sukatani, Kabupaten Purwakarta, Jawa Barat 41167',
                email: 'info@desasukatani.com',
                phone: '085846049091',
                fax: '085846049091',
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Dinas Sosial Pemberdayaan Perempuan dan Perlindungan Anak',
                logo: null,
                alias: 'DINSOSP3A',
                slug: 'dinsosp3a',
                address: 'Jl. Taman Pahlawan No. 9, Purwamekar, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41119',
                email: 'dinsosp3a@purwakartakab.go.id',
                phone: null,
                fax: null,
                url: 'https://dinsosp3a.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Dinas Kesehatan',
                logo: null,
                alias: 'DINKES',
                slug: 'dinkes',
                address: 'Jl. Veteran No.60, Nagri Kaler, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41115',
                email: 'purbakesa.dinkes@gmail.com',
                phone: '081212624150',
                fax: null,
                url: 'https://dinkes.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Dinas Pendidikan',
                logo: null,
                alias: 'DISDIK',
                slug: 'disdik',
                address: 'Jl. Surawinata No.30a, Nagri Tengah, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41114',
                email: null,
                phone: null,
                fax: null,
                url: 'https://disdik.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kecamatan Plered',
                logo: null,
                alias: 'PLERED',
                slug: 'plered',
                address: 'Jl. Raya Plered No.17, Plered, Kec. Plered, Kabupaten Purwakarta, Jawa Barat 41162',
                email: 'plered@purwakartakab.go.id',
                phone: null,
                fax: '0818150878',
                url: 'https://plered.purwakartakab.go.id',
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kecamatan Tegalwaru',
                logo: null,
                alias: 'TEGALWARU',
                slug: 'tegalwaru',
                address: 'Jl. Raya Warungjeruk, Sukahaji, Kec. Tegalwaru, Kabupaten Purwakarta, Jawa Barat 41111',
                email: null,
                phone: null,
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Dinas Perhubungan',
                logo: null,
                alias: 'DISHUB',
                slug: 'dishub',
                address: 'Jl. Veteran No.1, Ciseureuh, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41118',
                email: null,
                phone: '(0264) 200105',
                fax: null,
                url: 'https://dishub.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kecamatan Maniis',
                logo: null,
                alias: 'MANIIS',
                slug: 'maniis',
                address: 'Citamiang, Kec. Maniis, Kabupaten Purwakarta, Jawa Barat',
                email: null,
                phone: null,
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Badan Pendapatan Daerah',
                logo: null,
                alias: 'BAPENDA',
                slug: 'bapenda',
                address: 'Jl. Surawinata No.30A, Nagri Tengah, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41114',
                email: 'bapenda@purwakartakab.go.id',
                phone: '+62 82111336025',
                fax: null,
                url: 'https://bapenda.purwakartakab.go.id',
                type: 4,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: 'f509a247-35b7-11ee-903d-00155d74ec2a',
                name: 'Dinas Komunikasi dan Informatika',
                logo: null,
                alias: 'DISKOMINFO',
                slug: 'diskominfo',
                address: 'Jl. Gandanegara No.25, Nagri Kidul, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41111',
                email: 'info@diskominfo.purwakartakab.go.id',
                phone: '(0264) 200036',
                fax: null,
                url: 'https://diskominfo.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kecamatan Jatiluhur',
                logo: null,
                alias: 'JATILUHUR',
                slug: 'jatiluhur',
                address: 'Jl. Ir. H. Juanda No. 20, Jatiluhur, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41161',
                email: 'info@jatiluhur.purwakartakab.go.id',
                phone: '+62 264 208881',
                fax: null,
                url: 'https://jatiluhur.purwakartakab.go.id',
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: 'f509de24-35b7-11ee-903d-00155d74ec2a',
                name: 'Dinas Pekerjaan Umum dan Tata Ruang',
                logo: null,
                alias: 'DISTARKIM',
                slug: 'distarkim',
                address: 'Jl. KK Singawinata No. 116, Nagri Kidul, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat',
                email: 'distarkim@purwakartakab.go.id',
                phone: null,
                fax: null,
                url: 'https://distarkim.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kecamatan Sukasari',
                logo: null,
                alias: 'SUKASARI',
                slug: 'sukasari',
                address: 'Kertamanah, Kec. Sukasari, Kabupaten Purwakarta, Jawa Barat 41116',
                email: 'sukasari@purwakartakab.go.id',
                phone: '0818150878',
                fax: null,
                url: 'https://sukasari.purwakartakab.go.id',
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Dinas Koperasi UKM Perdagangan dan Perindustrian',
                logo: null,
                alias: 'DKUPP',
                slug: 'dkupp',
                address: 'Jl. Jend. Ahmad Yani No.170, Nagri Kaler, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41113',
                email: null,
                phone: '0264201064',
                fax: null,
                url: 'https://dkupp.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Dinas Pemadam Kebakaran dan Penanggulangan Bencana',
                logo: null,
                alias: 'DISKARPB',
                slug: 'diskarpb',
                address: 'Jl. A. Yani No.113, Cipaisan, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41113',
                email: 'diskarpb@purwakartakab.go.id',
                phone: null,
                fax: null,
                url: 'https://diskarpb.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kecamatan Babakancikao',
                logo: null,
                alias: 'BABAKANCIKAO',
                slug: 'babakancikao',
                address: 'Kadumekar, Kec. Babakancikao, Kabupaten Purwakarta, Jawa Barat 41151',
                email: 'babakancikao@gmail.com',
                phone: '+123 34598768',
                fax: null,
                url: 'https://babakancikao.purwakartakab.go.id',
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Badan Kepegawaian dan Pengembangan Sumber Daya Manusia',
                logo: null,
                alias: 'BKPSDM',
                slug: 'bkpsdm',
                address: 'Jl. Veteran, Komplek Perum Hegarmanah Kel. Ciseureuh, Kec. Purwakarta, Kab. Purwakarta, Jawa Barat 41118',
                email: 'bkpsdm@purwakartakab.go.id',
                phone: '(0264) 201019',
                fax: '(0264) 201019',
                url: 'https://bkpsdm.purwakartakab.go.id',
                type: 4,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: 'f50a932c-35b7-11ee-903d-00155d74ec2a',
                name: 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu',
                logo: null,
                alias: 'DPMPTSP',
                slug: 'dpmptsp',
                address: 'Jl. Veteran No. 139, Nagri Kaler, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41115',
                email: 'dpmptsp@purwakartakab.go.id',
                phone: '0264-8224794',
                fax: '0264-8224794',
                url: 'https://dpmptsp.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kecamatan Bungursari',
                logo: null,
                alias: 'BUNGURSARI',
                slug: 'bungursari',
                address: 'Jl. Veteran, Bungursari, Kec. Bungursari, Kabupaten Purwakarta, Jawa Barat 41181',
                email: null,
                phone: '(0264) 350272',
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Badan Penanggulangan Bencana Daerah',
                logo: null,
                alias: 'BPBD',
                slug: 'bpbd',
                address: 'Jl. Purnawarman Selatan, Sindangkasih, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41112',
                email: 'bpbdpurwakarta@gmail.com',
                phone: '+62 811-1440-117',
                fax: null,
                url: 'https://bpbd.purwakartakab.go.id',
                type: 4,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kecamatan Campaka',
                logo: null,
                alias: 'CAMPAKA',
                slug: 'campaka',
                address: 'Campaka, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41181',
                email: null,
                phone: null,
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'RSUD Bayu Asih',
                logo: null,
                alias: 'RSUD',
                slug: 'rsud',
                address: 'Jl. Veteran No.39, Nagri Kaler, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41115',
                email: 'rsud.bayuasih@gmail.com',
                phone: '0264200100',
                fax: null,
                url: 'https://rsudbayuasih.purwakartakab.go.id',
                type: 2,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kecamatan Cibatu',
                logo: null,
                alias: 'CIBATU',
                slug: 'cibatu',
                address: 'Jl. Raya Cibatu Km.15, Kec. Cibatu, Kabupaten Purwakarta, Jawa Barat 41181',
                email: null,
                phone: null,
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Badan Kesatuan Bangsa dan Politik',
                logo: null,
                alias: 'KESBANGPOL',
                slug: 'kesbangpol',
                address: 'Jl. Veteran No.153, Nagri Kaler, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41115',
                email: 'kesbangpolkabpurwakarta@gmail.com',
                phone: '(0264) 8941149',
                fax: null,
                url: 'https://kesbangpol.purwakartakab.go.id',
                type: 4,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kelurahan Nagri Kidul',
                logo: null,
                alias: 'NAGRIKIDUL',
                slug: 'nagrikidul',
                address: 'Jl. Kapten Halim No.75A, RT.25/RW.10, Nagri Kidul, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41111',
                email: null,
                phone: '(0264) 212105',
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Dinas Kepemudaan Olah Raga, Pariwisata dan Kebudayaan',
                logo: null,
                alias: 'DISPORAPARBUD',
                slug: 'disporaparbud',
                address: 'Jl. Purnawarman Timur No.2, Sindangkasih, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41112',
                email: 'disporaparbudpurwakarta@gmail.com',
                phone: '(0264) 8306540',
                fax: null,
                url: 'https://disporaparbud.purwakartakab.go.id',
                type: 5,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kelurahan Nagri Kaler',
                logo: null,
                alias: 'NAGRIKALER',
                slug: 'nagrikaler',
                address: 'Jl. Veteran No.7, Nagri Kaler, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41115',
                email: null,
                phone: '(0264) 201176',
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kelurahan Nagri Tengah',
                logo: null,
                alias: 'NAGRITENGAH',
                slug: 'nagritengah',
                address: 'Jl. Hidayat Martalogawa No.20, Nagri Tengah, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41114',
                email: null,
                phone: '(0264) 214445',
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kecamatan Purwakarta',
                logo: null,
                alias: 'PURWAKARTA',
                slug: 'purwakarta',
                address: 'Jl. Veteran No.58, Nagri Kaler, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41115',
                email: null,
                phone: '(0264) 201762',
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                name: 'Kelurahan Sindangkasih',
                logo: null,
                alias: 'SINDANGKASIH',
                slug: 'sindangkasih',
                address: 'Jl. Basuki Rahmat No. 34-36, Sindangkasih, Kec. Purwakarta, Kabupaten Purwakarta, Jawa Barat 41112',
                email: null,
                phone: null,
                fax: null,
                url: null,
                type: 1,
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
        ]);
        await Database_1.default.rawQuery('SET FOREIGN_KEY_CHECKS=1');
    }
}
exports.default = default_1;
//# sourceMappingURL=Governments.js.map