"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const Services_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Models/Services"));
const Database_1 = __importDefault(global[Symbol.for('ioc.use')]("Adonis/Lucid/Database"));
const Seeder_1 = __importDefault(global[Symbol.for('ioc.use')]("Adonis/Lucid/Seeder"));
const AttachmentLite_1 = global[Symbol.for('ioc.use')]("Adonis/Addons/AttachmentLite");
class default_1 extends Seeder_1.default {
    async run() {
        await Database_1.default.rawQuery('SET FOREIGN_KEY_CHECKS=0');
        await Services_1.default.createMany([
            {
                uuid: '8ef21945-405e-11ee-91c9-00155d8621c2',
                name: 'Call Center 112',
                logo: AttachmentLite_1.Attachment.fromDbResponse(JSON.stringify({
                    name: 'service/clllz0qgb01ucjbd65smm2i23.default.svg',
                    extname: 'svg',
                    size: 2310,
                    mimeType: 'image/svg',
                })),
                alias: '112',
                slug: '112',
                caption: 'Bantuan darurat, siap dalam satu panggilan cepat melalui Call Center 112.',
                url: 'https://purwakartakab.go.id/redirect?url=tel:112',
                sort: 1,
                government: 'f509a247-35b7-11ee-903d-00155d74ec2a',
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: '14e338ee-4061-11ee-91c9-00155d8621c2',
                name: 'Sampurasun Purwakarta',
                logo: AttachmentLite_1.Attachment.fromDbResponse(JSON.stringify({
                    name: 'service/clllznyng0084jpd6edye2hw7.default.svg',
                    extname: 'svg',
                    size: 4903,
                    mimeType: 'image/svg',
                })),
                alias: 'PISA',
                slug: 'pisa',
                caption: 'Laporkan keluhan dan aspirasimu melalui layanan berbasis WhatsApp.',
                url: 'https://wa.me/6287860142543',
                sort: 2,
                government: 'f509a247-35b7-11ee-903d-00155d74ec2a',
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: '5c4670c7-3a02-11ee-8c70-00155d14a14b',
                name: 'Wi-Fi Publik',
                logo: AttachmentLite_1.Attachment.fromDbResponse(JSON.stringify({
                    name: 'service/clld8fz3w0005g8d6djbr9u6m.default.svg',
                    extname: 'svg',
                    size: 2258,
                    mimeType: 'image/svg',
                })),
                alias: 'WIFI',
                slug: 'wifi',
                caption: 'Tetap terhubung dengan mudah melalui layanan Wi-Fi publik kami.',
                url: 'https://purwakartakab.go.id/gis/wifi',
                sort: 3,
                government: 'f509a247-35b7-11ee-903d-00155d74ec2a',
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: 'ff24da4b-4b9e-11ee-929b-00155d59a0bd',
                name: 'Trayek Angkot',
                logo: AttachmentLite_1.Attachment.fromDbResponse(JSON.stringify({
                    name: 'service/clm5s25qa00vejid6b02f4q5e.default.svg',
                    extname: 'svg',
                    size: 1803,
                    mimeType: 'image/svg',
                })),
                alias: 'ANGKOT',
                slug: 'angkot',
                caption: 'Nikmati mobilitas yang mudah dengan berbagai rute angkot.',
                url: 'https://purwakartakab.go.id/gis/angkot',
                sort: 4,
                government: 'f509a247-35b7-11ee-903d-00155d74ec2a',
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: 'c843dd67-3a03-11ee-8c70-00155d14a14b',
                name: 'Hotel',
                logo: AttachmentLite_1.Attachment.fromDbResponse(JSON.stringify({
                    name: 'service/clld8t2b9000561d62f07hs3t.default.svg',
                    extname: 'svg',
                    size: 1041,
                    mimeType: 'image/svg',
                })),
                alias: 'HOTEL',
                slug: 'hotel',
                caption: 'Temukan akomodasi nyaman di Purwakarta sesuai kebutuhan kamu.',
                url: 'https://purwakartakab.go.id/gis/hotel',
                sort: 5,
                government: 'f509a247-35b7-11ee-903d-00155d74ec2a',
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: 'e131018f-3a03-11ee-8c70-00155d14a14b',
                name: 'Wisata',
                logo: AttachmentLite_1.Attachment.fromDbResponse(JSON.stringify({
                    name: 'service/clld8tyl4000b61d6dq429zk6.default.svg',
                    extname: 'svg',
                    size: 1009,
                    mimeType: 'image/svg',
                })),
                alias: 'WISATA',
                slug: 'wisata',
                caption: 'Jelajahi pesona alam dan budaya melalui destinasi wisata menarik.',
                url: 'https://purwakartakab.go.id/gis/wisata',
                sort: 6,
                government: 'f509a247-35b7-11ee-903d-00155d74ec2a',
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: 'f6eea424-3a03-11ee-8c70-00155d14a14b',
                name: 'Wisata Kuliner',
                logo: AttachmentLite_1.Attachment.fromDbResponse(JSON.stringify({
                    name: 'service/clld8uqqc000h61d6fy4b0xpz.default.svg',
                    extname: 'svg',
                    size: 1309,
                    mimeType: 'image/svg',
                })),
                alias: 'KULINER',
                slug: 'kuliner',
                caption: 'Nikmati kelezatan kuliner khas yang akan memanjakan lidah kamu.',
                url: 'https://purwakartakab.go.id/gis/kuliner',
                sort: 7,
                government: 'f509a247-35b7-11ee-903d-00155d74ec2a',
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: 'a55bc938-3ff6-11ee-8858-00155d14a65a',
                name: 'Permohonan Informasi',
                logo: AttachmentLite_1.Attachment.fromDbResponse(JSON.stringify({
                    name: 'service/cllklcwod00684dd65xm482co.default.svg',
                    extname: 'svg',
                    size: 2474,
                    mimeType: 'image/svg',
                })),
                alias: 'PPID',
                slug: 'ppid',
                caption: 'Sampaikan permohonan informasi secara online dengan mudah.',
                url: 'https://ppid.purwakartakab.go.id',
                sort: 8,
                government: 'f509a247-35b7-11ee-903d-00155d74ec2a',
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: '318036af-3a11-11ee-8c70-00155d14a14b',
                name: 'OganLopian',
                logo: AttachmentLite_1.Attachment.fromDbResponse(JSON.stringify({
                    name: 'service/clldc8irm00gu8hd6a8qv1xn9.default.svg',
                    extname: 'svg',
                    size: 2156,
                    mimeType: 'image/svg',
                })),
                alias: 'OGANLOPIAN',
                slug: 'oganlopian',
                caption: 'Satu aplikasi, tanpa batas - wisata dan belanja, semua ada di ujung jari!',
                url: 'https://play.google.com/store/apps/details?id=id.co.pratamatechsolution.oganlopian',
                sort: 9,
                government: 'f509a247-35b7-11ee-903d-00155d74ec2a',
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: '9487afaa-3a1a-11ee-8c70-00155d14a14b',
                name: 'LPSE Purwakarta',
                logo: AttachmentLite_1.Attachment.fromDbResponse(JSON.stringify({
                    name: 'service/clldeqhxd011r8hd6gtkigyyb.default.svg',
                    extname: 'svg',
                    size: 1297,
                    mimeType: 'image/svg',
                })),
                alias: 'LPSE',
                slug: 'lpse',
                caption: 'Layanan penyelenggara sistem elektronik pengadaan barang&#x2F;jasa.',
                url: 'https://lpse.purwakartakab.go.id/eproc4',
                sort: 10,
                government: 'f5073c94-35b7-11ee-903d-00155d74ec2a',
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: '7d84c6ed-3a15-11ee-8c70-00155d14a14b',
                name: 'DPMPTSP Purwakarta',
                logo: AttachmentLite_1.Attachment.fromDbResponse(JSON.stringify({
                    name: 'service/cllddc2s700y08hd6es798a6v.default.svg',
                    extname: 'svg',
                    size: 3439,
                    mimeType: 'image/svg',
                })),
                alias: 'DPMPTSP',
                slug: 'dpmptsp',
                caption: 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu.',
                url: 'https://dpmptsp.purwakartakab.go.id',
                sort: 11,
                government: 'f50a932c-35b7-11ee-903d-00155d74ec2a',
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: '0be45c83-3a10-11ee-8c70-00155d14a14b',
                name: 'Papais CCTV',
                logo: AttachmentLite_1.Attachment.fromDbResponse(JSON.stringify({
                    name: 'service/clldc3j1800eq8hd692gnawzv.default.svg',
                    extname: 'svg',
                    size: 1727,
                    mimeType: 'image/svg',
                })),
                alias: 'PAPAIS',
                slug: 'papais',
                caption: 'Pantau arus lalu lintas secara langsung di beberapa titik vital.',
                url: 'https://cctv.purwakartakab.go.id',
                sort: 12,
                government: 'f509a247-35b7-11ee-903d-00155d74ec2a',
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: '0bba1214-3a13-11ee-8c70-00155d14a14b',
                name: 'Investasi',
                logo: AttachmentLite_1.Attachment.fromDbResponse(JSON.stringify({
                    name: 'service/clldcpko300qi8hd66vl778vx.default.svg',
                    extname: 'svg',
                    size: 1482,
                    mimeType: 'image/svg',
                })),
                alias: 'INVESTASI',
                slug: 'investasi',
                caption: 'Dapatkan informasi terkait potensi dan peluang investasi di Purwakarta.',
                url: 'https://investasi.purwakartakab.go.id',
                sort: 13,
                government: 'f50a932c-35b7-11ee-903d-00155d74ec2a',
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: 'b6360ead-3a14-11ee-8c70-00155d14a14b',
                name: 'Kalkulator PBG',
                logo: AttachmentLite_1.Attachment.fromDbResponse(JSON.stringify({
                    name: 'service/clldd4wrs00uj8hd69wpqad7r.default.svg',
                    extname: 'svg',
                    size: 4850,
                    mimeType: 'image/svg',
                })),
                alias: 'SIKARET',
                slug: 'sikaret',
                caption: 'Simulasi Perhitungan Persetujuan Bangunan Gedung Baru dan Renovasi.',
                url: 'https://sikaret.purwakartakab.go.id',
                sort: 14,
                government: 'f509de24-35b7-11ee-903d-00155d74ec2a',
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: '2a55d4e3-3a12-11ee-8c70-00155d14a14b',
                name: 'JDIH Purwakarta',
                logo: AttachmentLite_1.Attachment.fromDbResponse(JSON.stringify({
                    name: 'service/clldchgw600ni8hd610an0hjf.default.svg',
                    extname: 'svg',
                    size: 1980,
                    mimeType: 'image/svg',
                })),
                alias: 'JDIH',
                slug: 'jdih',
                caption: 'Jaringan Dokumentasi dan Informasi Hukum Pemerintah Daerah.',
                url: 'https://jdih.purwakartakab.go.id',
                sort: 15,
                government: 'f5073c94-35b7-11ee-903d-00155d74ec2a',
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
            {
                uuid: '41155d16-3a14-11ee-8c70-00155d14a14b',
                name: 'WebGIS',
                logo: AttachmentLite_1.Attachment.fromDbResponse(JSON.stringify({
                    name: 'service/clldd0p5400sv8hd676sf1rpa.default.svg',
                    extname: 'svg',
                    size: 1160,
                    mimeType: 'image/svg',
                })),
                alias: 'SIDIKA',
                slug: 'sidika',
                caption: 'Temukan Purwakarta lebih dalam dengan informasi lokal interaktif.',
                url: 'https://webgis.purwakartakab.go.id',
                sort: 16,
                government: 'f509de24-35b7-11ee-903d-00155d74ec2a',
                enhancer: '454342ac-ea26-11ed-8a6a-00155dd467fd',
            },
        ]);
        await Database_1.default.rawQuery('SET FOREIGN_KEY_CHECKS=1');
    }
}
exports.default = default_1;
//# sourceMappingURL=Services.js.map