"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const Env_1 = __importDefault(global[Symbol.for('ioc.use')]("Adonis/Core/Env"));
exports.default = Env_1.default.rules({
    HOST: Env_1.default.schema.string({ format: 'host' }),
    PORT: Env_1.default.schema.number(),
    NODE_ENV: Env_1.default.schema.enum(['development', 'production']),
    APP_URL: Env_1.default.schema.string(),
    APP_FRONT: Env_1.default.schema.string(),
    APP_NAME: Env_1.default.schema.string(),
    APP_KEY: Env_1.default.schema.string(),
    DRIVE_DISK: Env_1.default.schema.enum(['local', 's3']),
    SESSION_DRIVER: Env_1.default.schema.string(),
    CACHE_VIEWS: Env_1.default.schema.boolean(),
    HASH_DRIVER: Env_1.default.schema.enum(['scrypt', 'argon', 'bcrypt']),
    CACHE_DRIVER: Env_1.default.schema.string(),
    DB_CONNECTION: Env_1.default.schema.string(),
    MYSQL_HOST: Env_1.default.schema.string({ format: 'host' }),
    MYSQL_PORT: Env_1.default.schema.number(),
    MYSQL_USER: Env_1.default.schema.string(),
    MYSQL_PASSWORD: Env_1.default.schema.string.optional(),
    MYSQL_DB_NAME: Env_1.default.schema.string(),
    REDIS_CONNECTION: Env_1.default.schema.enum(['local']),
    REDIS_HOST: Env_1.default.schema.string({ format: 'host' }),
    REDIS_PORT: Env_1.default.schema.number(),
    REDIS_PASSWORD: Env_1.default.schema.string.optional(),
    SMTP_HOST: Env_1.default.schema.string({ format: 'host' }),
    SMTP_PORT: Env_1.default.schema.number(),
    SMTP_USERNAME: Env_1.default.schema.string(),
    SMTP_PASSWORD: Env_1.default.schema.string(),
    S3_KEY: Env_1.default.schema.string(),
    S3_SECRET: Env_1.default.schema.string(),
    S3_BUCKET: Env_1.default.schema.string(),
    S3_REGION: Env_1.default.schema.string(),
    S3_ENDPOINT: Env_1.default.schema.string.optional(),
    BPS_APP_ID: Env_1.default.schema.string(),
    BPS_DOMAIN: Env_1.default.schema.number(),
    BPS_LANG: Env_1.default.schema.enum(['ind', 'eng']),
    GMAPS_APIKEY: Env_1.default.schema.string(),
    GMAPS_LATITUDE: Env_1.default.schema.string(),
    GMAPS_LONGITUDE: Env_1.default.schema.string(),
    PST_PARIWISATA: Env_1.default.schema.string(),
    PST_PROKOMPIM: Env_1.default.schema.string(),
    BULL_REDIS_HOST: Env_1.default.schema.string({ format: 'host' }),
    BULL_REDIS_PORT: Env_1.default.schema.number(),
    BULL_REDIS_PASSWORD: Env_1.default.schema.string.optional(),
    PUBLIC_VAPID_KEY: Env_1.default.schema.string(),
    PRIVATE_VAPID_KEY: Env_1.default.schema.string(),
    SENTRY_DSN: Env_1.default.schema.string({ format: 'url', protocol: true, tld: true }),
    POSTMAN_COLLECTION: Env_1.default.schema.string.optional({ format: 'url', protocol: true, tld: true }),
});
//# sourceMappingURL=env.js.map